spring.application.name=StudentBackend
spring.datasource.url=jdbc:mysql://localhost:3306/fsds53
spring.datasource.username=root
spring.datasource.password=Bhavitha@2400033317

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081