spring.datasource.url=jdbc:mysql://localhost:3306/product_db_skill8
spring.datasource.username=root
spring.datasource.password=Bhavitha@2400033317

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8086